# Generated by Django 5.0.3 on 2024-03-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('weeks', 'недель'), ('months', 'месяцев'), ('years', 'лет')], default='months')),
            ],
        ),
    ]
