# Generated by Django 5.0.3 on 2024-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='icon_link',
            field=models.CharField(null=True),
        ),
    ]
