version: "3"

services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: education
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123*
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "education", "-U", "admin" ]
      interval: 30s
      timeout: 60s
      retries: 5