# Generated by Django 5.0.3 on 2024-03-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file_link', models.CharField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_material_id', to='Courses.courses')),
            ],
        ),
    ]
