# Generated by Django 5.0.3 on 2024-03-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_id', to='Courses.courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
